version: '3.7'

services:
  postgres:
      image: postgres
      container_name: postgres
      restart: always
      privileged: true
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=123456
          - POSTGRES_DB=postgres
      user: root
      ports:
          - "5432:5432"
      volumes:
          - /home/modanez/volumes/postgres/data:/var/lib/postgresql/data
      networks:
        - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "wesley.modanez@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
