version: '3'

services:
  postgres-compose:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:z
    networks:
      - postgres-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "wesley.modanez@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
